# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

update_fastlane

default_platform(:ios)

platform :ios do
    desc "Build only"
    lane :build do
        # Resolve the Swift Package Manager dependencies
        xcodebuild(
            build: false,
            xcargs: "-resolvePackageDependencies",
        )

        # Build the PrototyperExample application without tests
        xcodebuild(
            scheme: "Prototyper Example",
            configuration: "Debug",
            clean: true,
            build: true,
            build_settings: {
                "CODE_SIGNING_ALLOWED" => "NO",
                "CODE_SIGNING_REQUIRED" => "NO",
                "CODE_SIGN_IDENTITY" => "",
                "CODE_SIGN_ENTITLEMENTS" => "",
            }
        )
    end

    desc "Build a release version of the app for Prototyper"
    lane :release do
        # Setup ENV variables
        ENV['FASTLANE_PASSWORD'] = ENV['bamboo_FASTLANE_PASSWORD'] # Necessary for unlocking the key chain
        ENV['FASTLANE_SESSION'] = ENV['bamboo_FASTLANE_SESSION_PASSWORD'] # Necessary for 2FA 
        INFO_PLIST = "./Prototyper Example/Info.plist" # Location of the info.plist in the folder structure
        ENV['PROTOTYPER_BUILDSTRING'] = sh("date", "+%y%m%d_%H%M").rstrip + "-build" + (ENV['bamboo_buildNumber'] ||= "") + "-" + (ENV['bamboo_repository_branch_name'] ||= "") # Prototyper Buildstring to identify releases

        # Write Prototyper BuildString to Info.plist
        set_info_plist_value(
            path: INFO_PLIST,
            key: "CFBundleVersion",
            value: "$(PROTOTYPER_BUILDSTRING)"
        )

        # Unlock the agent key chain to gain access to the necessary certificates
        unlock_keychain(
            path: ENV['bamboo_KeyChain'],
            password: ENV['bamboo_KeyChainPassword'],
        )

        # Invoke fastlane sigh to get the app provisioned
        get_provisioning_profile(
            username: ENV['bamboo_FASTLANE_USER'],
            team_id: ENV['bamboo_FASTLANE_TEAM_ID'],
        )

        # Build the app
        build_ios_app(
            output_directory: "./",
            output_name: "BuildedApplication.ipa",
            export_method: "enterprise",
            buildlog_path: "./",
            archive_path: "./BuildedApplication",
            codesigning_identity: ENV['bamboo_CodeSigningIdentity'],
            configuration: "Release",
        )

        # Create Build String
        sh "echo $PROTOTYPER_BUILDSTRING > BuildString.txt"
        sh "mv BuildString.txt ../"
    end
end
