name: Publish Documentation

on:
  release:
    types: [published]

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Generate Xcode project
      run: swift package generate-xcodeproj
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        args: "--config .jazzy.yml --swift-build-tool xcodebuild --build-tool-arguments -sdk,iphoneos,-scheme,Prototyper"
