name: Build and Test

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop, release ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
     - name: Xcode 12.0
      run: sudo xcode-select -s 
    - name: Check Swift version
      run: swift --version
    - name: Generate Xcode project
      run: swift package generate-xcodeproj
    - name: Build
      run: xcodebuild build -sdk iphoneos -scheme 'Prototyper-Package'
    - name: Test
      run: xcodebuild test -destination 'name=iPhone 11 Pro' -scheme 'Prototyper-Package'
